### ISSUE TITLE
Approval of Application should be directed to IS as first approver then Admin/HR

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#10]
The application for alteration, leave etc goes to the account of the Admin/HR of the plant.

I had the access to the Admin/HR account . The application went through me and prompted an option for approval.
Application  should not go directly to HR for approval but should go to IS for first approval, then there should be a secondary approval for HR in charge. The application should prompt that the application is subject or first approval then give an option for my approval when it is already subject for second approval.

Device Details:
Laptop
Windows 10
Browser Google Chrome

**Comment by VCI-Jojo** [comment]
@Annagwind We've added a feature on the employee profile under HR > Employees section where you can select the first and second approvers. Kindly validate on your account. Thank you.

**Comment by Annagwind** [comment]
Hi Sir I encountered a problem with the system. When the 1st approval was given the application for alteration went to my account for secondary approval but when I tried to click approve all the pending request disappeared and was no longer available for my approval.

**Comment by VCI-Jojo** [comment]
@Annagwind Please click on the "Show Approved ..." and see if you still have the approved applications there. Also, do you have the "Feedback" button or reporting tool on your account, if so, please use that to report so it can capture the browser and error information if any. Thank you.

Screenshot for reference below:
![show approved](https://user-images.githubusercontent.com/64577963/91384415-1d580180-e861-11ea-9010-e009e43fa550.PNG)

**Comment by Annagwind** [comment]
Where can the feedback button or reporting tool can be located?


Thank you and best regards.

**Comment by VCI-Jojo** [comment]
I'll guide you later during the alignment meeting so I can explain to everyone the reporting tool (feedback button). Thanks

**Comment by Annagwind** [comment]
The approval now is directed to IS for 1st approval.

**Comment by VCI-Jojo** [comment]
This is noted. Closing this ticket.
