### ISSUE TITLE
KODANDA issues & Concerns

### ISSUE THREAD

**Issue by Eviloria12** [vasavah/acenergykodanda#106]
Hi,

Good Afternoon.

Here are the following Issues of Northwind Personnel regarding Kodanda: 

Pending approval for the last working schedule of WTG & TSD. They cannot apply new working schedule for the upcoming month. (Please see attached screenshot)
No current and previous payslip viewing.
Kodanda loads slower even changing and using better source of internet. (Please see below screenshot sample of Punch In and Punch Out).

Appreciate your assistance on this matter.

![Change Work Schedule ](https://user-images.githubusercontent.com/72014444/97261991-f0bd6780-185a-11eb-82b2-d340213a0780.jpg)
![Kodanda Punch In and Out](https://user-images.githubusercontent.com/72014444/97262001-f3b85800-185a-11eb-816b-1a63b77a0eab.jpg)
![Work Schedule](https://user-images.githubusercontent.com/72014444/97262016-fa46cf80-185a-11eb-9f10-7d8fc05381f4.jpg)

**Comment by VCI-Jojo** [comment]
@Eviloria12 For this clarification: No current and previous payslip viewing, it will be activated upon the deployment of the Payroll Module.  For the other concerns reported, the support team will email once patch has been applied to the instance. Thank you.
