### ISSUE TITLE
Payroll Register Generated does not match

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#109]
I Generated October 1-15 payroll register of Supervisor but generated payroll reflects period covered reflects September 16-30 Rank and File  

Contents are Supervisory Employee

Note : "Period Period"

![KODANDA 2](https://user-images.githubusercontent.com/68258969/97554525-da0d4100-1a11-11eb-9aab-a609d744570a.PNG)
![KODANDA 1](https://user-images.githubusercontent.com/68258969/97554529-dbd70480-1a11-11eb-95a2-39b567df4858.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind I checked the created TAR for October 1-15 is reflected on the TAR cutoff as per screenshots provided below:

![Supervisory GW](https://user-images.githubusercontent.com/64577963/97651420-ed162480-1a96-11eb-9120-8ec2a06779e3.PNG)

![Supervisory GW TAR](https://user-images.githubusercontent.com/64577963/97651426-f1dad880-1a96-11eb-8ec3-03b721464340.PNG)

Kindly recheck the TAR generated. Thank you.

**Comment by Annagwind** [comment]
I was referring to Generated Payroll Register in my screenshot. your screen shot is relative to the TAR.

**Comment by VCI-Jojo** [comment]
This is noted, we are checking the concern now and will keep you posted regarding its resolution.

**Comment by Annagwind** [comment]
https://github.com/vasavah/acenergykodanda/issues/103
