### ISSUE TITLE
Application of OT

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#11]
Supervisory Employees have the option to apply for OT in the system.

The Employees classified as supervisory should not have the option to apply for OT. Instead they can apply for ADO Credit or ADO Availment.  

Device Details:
Laptop
Windows 10
Browser Google Chrome

**Comment by VCI-Jojo** [comment]
@Annagwind We are working on the CTO/ADO feature and should be able to endorse this within the week so Supervisory Employees can opt to apply for ADO credit instead of OT. I'll keep you posted regarding the progress.

**Comment by VCI-Jojo** [comment]
@Annagwind CTO/ADO function has been activated in all ACE companies, linking this to ticket #25
