### ISSUE TITLE
System Lag for GC Unida's Kodanda Account

### ISSUE THREAD

**Issue by bajetdj** [vasavah/acenergykodanda#111]
System Lagging for Gilbert C. Unida's Kodanda Account. Wasn't able to punch in and out because it was stocked up/freeze on October 19.

![Screenshot_20201030-155249_Samsung Internet](https://user-images.githubusercontent.com/73638708/97767471-32019000-1b57-11eb-804d-e493ed903059.jpg)

**Comment by zetaleona** [comment]
![image](https://user-images.githubusercontent.com/50394125/98061555-0e0bba80-1e87-11eb-8df0-ef8df3a4608e.png)


Punch buttons are already active and the user can be able to time-In and Time-Out, This is for your closing @byron


I test also on mobile and it's active also
![image](https://user-images.githubusercontent.com/50394125/98061694-69d64380-1e87-11eb-8163-1dd619112528.png)
