### ISSUE TITLE
Day shift Operator OT Treatment

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#12]
Day Shift Operators are usually assigned to various shift schedule such as 8am-5pm shift, 1st shift, 2nd shift and 3rd Shift. 

When scheduled as Day Shift, rank and file employees are given OT for the entire time they report for work since this is in excess of the minimum work hours  . How do we treat this ? Pre Shift or Post Shift?
Can the system provide an option for day shift schedule ?

**Comment by VCI-Jojo** [comment]
@Annagwind As discussed with Abbie, she will do an internal meeting with you regarding the policy for this one. Thank you.
