### ISSUE TITLE
TOTAL DAYS NOT ACCURATE

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#128]
Mr. Ferrer has a Mon-Sat Work schedule. Number of working days during oct 16-31 cut off is 14. Data does not match in generated consolidated tar.
![RFF WD](https://user-images.githubusercontent.com/68258969/97882240-5b403d00-1d5e-11eb-85b3-9d968d1b0ace.PNG)

**Comment by Annagwind** [comment]
Mr. Coo is part of the shifting schedule of operators and was given 2 days off during the Oct 16-31 cut off.Total Days should be 14.

Kindly confirm

![BLC wd](https://user-images.githubusercontent.com/68258969/97885275-1cac8180-1d62-11eb-9e3f-170d6d01c374.PNG)

**Comment by Annagwind** [comment]
Mr. Templanza, Ms. Ganea , Mr. Balatayo, & Mr. Galon has 14 Working Days during the Oct 16-31cut off. Mon-Sat schedule.

Mr. Garganta has 11 Working days during the Oct 16-31 cut off . Mon-Fri Schedule

![SE WD](https://user-images.githubusercontent.com/68258969/97888274-f1c42c80-1d65-11eb-859e-b95eff8618a6.PNG)

**Comment by zetaleona** [comment]
@byron, there's a connected issue on this ticket approved leaves status are still absent

Reference: maria.antonio
org. smudgecorp
reference: https://app.kodanda.cloud/time-records/list
reference dtr: https://app.kodanda.cloud/register/cutoff/dtr/NeLRY45SvO2imMzR/YRnuW9MPoFVvqkfO/NeLRY45SvO2imMzR_YRnuW9MPoFVvqkfO_dtr_97
                 
![image](https://user-images.githubusercontent.com/50394125/98203565-3ec71f00-1f6f-11eb-9866-6a5c1260d1a6.png)
 

![image](https://user-images.githubusercontent.com/50394125/98203476-18a17f00-1f6f-11eb-887a-7349604c2c01.png)

**Comment by Byron** [comment]
I think you mean to refer to a different person.
