### ISSUE TITLE
Leave Credit Error

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#13]
As I was doing the crediting of leave options. I accidentally added 2 sick leave options to Mr. Coo. How do we delete this ? 

The system should have the option to delete the leave credit in the event of errors in crediting such as this one.

![Sick Leave](https://user-images.githubusercontent.com/68258969/89485323-1c3c3300-d7d3-11ea-8594-691f55c5c473.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind We've added a "Delete" button for this, kindly validate on your end if you are able to remove the incorrect leave credits. Thank you.

**Comment by Annagwind** [comment]
Confirming this is already functioning.

**Comment by VCI-Jojo** [comment]
This is noted. Closing this ticket.
