### ISSUE TITLE
Employees Leave Credits not found/no records

### ISSUE THREAD

**Issue by bajetdj** [vasavah/acenergykodanda#133]
No records found in HR__Employees__Leave Credit (no records for all CIP employees)

![image](https://user-images.githubusercontent.com/73638708/97947351-01745d00-1dc8-11eb-96ac-066085c029c2.png)

**Comment by bajetdj** [comment]
I only have this 8 records, no records for all the employees.

**Comment by VCI-Jojo** [comment]
@bajetdj Upon checking the CIPII instance, employee list and leave credits are complete, checking your screenshot though, it seems that this is for MCV Bulk Water? Please clarify as they have only a few employees on their list. Thank you.

**Comment by bajetdj** [comment]
Hi Sir Joe,

I got this screenshot from my own HR Access.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by VCI-Jojo** [comment]
@bajetdj Kindly confirm if this the URL you are accessing: https://app.kodanda.cloud/login/cipii

**Comment by bajetdj** [comment]
Yes Sir, confirming url

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
