### ISSUE TITLE
switched up access/profile

### ISSUE THREAD

**Issue by emsarmiento** [vasavah/acenergykodanda#15]
Access of Berlee Catalan and Jezreel Catalan have switched up.

After they logged in using their respective username and password, they're directed into wrong profiles.

**Comment by VCI-Jojo** [comment]
@emsarmiento I'll have this validated by the support team and will keep you posted on the investigation and/or resolution.

May we know also which instance/company they belong to? Thank you.

**Comment by emsarmiento** [comment]
@VCI-Jojo hi Jojo, this is from ACE Endevor. thanks!

**Comment by VCI-Jojo** [comment]
@emsarmiento Upon checking the data sheets, their information was interchanged, we corrected it on the system tho so kindly validate on your end. Thank you.
