### ISSUE TITLE
Leave Features

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#16]
As I was exploring the features of the Leave in HR tab.  I've noticed that the previous year balance of VL is not included every employee is entitled to 15 days VL current (plus unused VL of last year)  and 15 days  SL for the current year. I suggest that the there should be a column for the previous year unused VL. 

For improvement of the system the following features should be considered: 
1. Unused VL (Previous year)- The unused VL of last yeae should be made available to be used first in the current year before using the current year VL credits. This expires every June of the current year. The system to deduct the leave application of the current year here first. If the previous year balance is already used that is when the system should prompt the user that the application will charged to the current year VL.

2. Current VL -15 Days- This should be utilized after the use of the previous year VL Balance.

3. Used VL column-This is currently un editable but since the employees already used their credit this year I hope this could be editable to show how many leaves were used before the system was implemented or allow the admin to encode the leave history for this year.  This will allow us to tract the leave history for the entire year.

4. REMAINING-This should be computed automatically the results of = Unused VL+Current VL-Used VL

5. When Applying for leave I hope that the system could show the users the remaining balance for the VL and SL credit to show them the balance before any submission. When submitted it will be better if the approver could also see the remaining leave credit to take in consideration the remaining balance if he/she approves the application, (This is being done in our manual tracking)

![UNABLE TO EDIT USED](https://user-images.githubusercontent.com/68258969/90305052-ccefb400-def0-11ea-933f-dbf3eebb03ff.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind Thank you for the feedback. This is already an enhancement so will need to be discussed with Abbie. Thanks you.
