### ISSUE TITLE
Unable to Access 1-15 Data in the 16th day of the month

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#17]
It's currently the 16th day of the month. The employees would need to finalized their entries in the system for the 1-15 cut off. They've noticed that their data is no longer available in the "Time Records" tab. The system should allow the data to be available for the users  atleast 1 week to 1 month after every cut off. There might be entries in the 15th day that need to be finalized in the 16th.  A folder for the monthly records will be helpful in tracking down the previous data also
![Unable to access previous data](https://user-images.githubusercontent.com/68258969/90325060-52cf3600-dfa9-11ea-900c-db5f27360c49.PNG)
.

**Comment by VCI-Jojo** [comment]
@Annagwind We've applied the adjustments for this so kindly validate on your end if you the data is available. Thank you.
