### ISSUE TITLE
[Kiosk] Still requesting for activation but added already to authorized list

### ISSUE THREAD

**Issue by VCI-Jojo** [vasavah/acenergykodanda#171]
Added to authorized list but kiosk is still requesting for activation:

![Yael - Authorized](https://user-images.githubusercontent.com/64577963/100837910-73fe5880-34ac-11eb-8926-b41378f80bdb.PNG)

End user kiosk:

![0-02-06-e61f4c5eaf6e5745203321e9f673cc5abb09a9269974c66e231184c067fa27e2_abbcd204](https://user-images.githubusercontent.com/64577963/100837975-91332700-34ac-11eb-9938-cd599861a2d2.jpg)

**Comment by Annagwind** [comment]
Same issue with GW Users. Already added their device with the same location as kiosk but still requesting for authentication.
