### ISSUE TITLE
LEAVE AND ADO CREDITS

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#175]
![image](https://user-images.githubusercontent.com/68258969/101711387-68bfb400-3ace-11eb-8739-a38b311e4f35.png)

**Comment by VCI-Jojo** [comment]
@Annagwind May we know the concern for the Leave Credits and ADO? Thank you

**Comment by Annagwind** [comment]
There are certain times when I try to check the leave feature that I what appears on my screen are not GW related employees. Example can be seen in the screenshot of this ticket.
