### ISSUE TITLE
Unable to apply alteration on previous Cut Off 

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#18]
The employees of GW was about to finalize their entries in the system and they've noticed that they are unable to apply for alteration for the 1-15 entries. They only available data to be applied any Alteration is the  "June 16-30" Cut off. The system should allow the users to apply for any alteration for the past cut off before the applications will be locked.
![Cut Off Issues](https://user-images.githubusercontent.com/68258969/90325144-9c6c5080-dfaa-11ea-979a-78f442ade1bd.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind They should be able to access this already, kindly validate on your end. Thank you.
