### ISSUE TITLE
Cutt off on Generating Daily Time Record

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#19]
As I was exploring the Register Tab, I tried to generate the records for Aug 1-15 but as seen in the screen shot the cut off available is only June 16-30. 

The system should allow the admin access to view all entries of the employees to all the previous
![Cut off Issues 3](https://user-images.githubusercontent.com/68258969/90325199-346a3a00-dfab-11ea-804e-65411d7e49ce.PNG)
 cut off.

**Comment by VCI-Jojo** [comment]
@Annagwind I'll guide you guys later during the alignment meeting so you can view the previous cutoffs. Thanks

**Comment by VCI-Jojo** [comment]
As per our meeting earlier, you can check the cutoffs list under the register you are accessing.

**Comment by Annagwind** [comment]
confirming this is already functioning.

**Comment by VCI-Jojo** [comment]
This is noted. Closing this ticket.
