### ISSUE TITLE
Absent even though application for alteration or leave is approved

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#20]
Mr. Templanza filed for Leave application last Aug 20, 2020  and his application was approved last August 27, 2020.

Upon checking his time records it has come to his attention that his entries for August 22, 2020 (the approved leave date) reflects that he is absent.

Ms. Ganea also experienced that her alterations was approved but it reflects that she is Absent.

![Approve Leave](https://user-images.githubusercontent.com/68258969/91507526-a1fd5b00-e907-11ea-984f-a7a6fe6b278d.PNG)
![Time in-Time out](https://user-images.githubusercontent.com/68258969/91507532-a7f33c00-e907-11ea-82a0-d32211f45e00.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind I'll have this checked and resolved today. I'll keep you posted. Thank you.

**Comment by VCI-Jojo** [comment]
@Annagwind We've applied the fix for the Approved Leaves and Alterations, please validate on your end. Thank you.
