### ISSUE TITLE
ADO feature

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#22]
I have included ADO Feature to supervisors to avail and input the maximum 48 days for ADO per year. 

Do you have the procedure to apply for the crediting ? or will this be done manually?

![ADO ISSUE](https://user-images.githubusercontent.com/68258969/91512011-957eff80-e913-11ea-9224-c97a9f250c3d.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind As discussed during our alignment meeting last week, you will need to change the Superviros/Managers Roster to ManagerCTO so that their overtimes will be converted to Compensatory Time Off (CTO) or in your case ADO (Additional Day Off). Thank you.
