### ISSUE TITLE
Approved Official Business Travel 

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#23]
Mr. Ferrer applied for official business travel from August 16-28, 2020, Upon checking his online access even though his application was approved it reflected that he is ABSENT.

The system should reflect that he was on travel on those dates. There will be an error on the payroll if it reflects that he is absent on those dates rather than he is on travel.l  

![rff travel](https://user-images.githubusercontent.com/68258969/91514953-9f583100-e91a-11ea-851e-5d4e881197fb.PNG)

![rff travel 2](https://user-images.githubusercontent.com/68258969/91514948-9d8e6d80-e91a-11ea-8a57-e71ea9e7eb45.PNG)

![rff 3](https://user-images.githubusercontent.com/68258969/91515019-cadb1b80-e91a-11ea-886d-84e69b7dca10.PNG)

**Comment by Annagwind** [comment]
This is also experienced by all GW users.

**Comment by Annagwind** [comment]
The Time Records now show that you are on Official Business Travel.

Thanks.

**Comment by VCI-Jojo** [comment]
@Annagwind We've applied the fix for the Approved Leaves and Official Business, please validate on your end. Thank you.
