### ISSUE TITLE
Irregular Schedule – should be customized as such rather than having to select one.  Employee’s schedule varies everyday. 

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#235]
Irregular Schedule – should be customized as such rather than having to select one.  Employee’s schedule varies everyday.  Zen Hours setting employee applies the work schedule in advance. 

![image](https://user-images.githubusercontent.com/68258969/104890750-f4204500-59aa-11eb-8b50-b64fd2671f9f.png)
![image](https://user-images.githubusercontent.com/68258969/104890762-f7b3cc00-59aa-11eb-9541-f876b178f272.png)

**Comment by VCI-Jojo** [comment]
@Annagwind this is done via the Change Work Schedule module.
