### ISSUE TITLE
HDMF Contri Should be 100

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#239]
![image](https://user-images.githubusercontent.com/68258969/104892001-9987e880-59ac-11eb-9da2-08101dcb83f6.png)

**Comment by VCI-Jojo** [comment]
@Annagwind May we get the username and basic rate of the user? Thank you

**Comment by Annagwind** [comment]
user: tormis.j
HDMF Contri should be 100 per month
