### ISSUE TITLE
Unable to log in (Endevor)

### ISSUE THREAD

**Issue by emsarmiento** [vasavah/acenergykodanda#24]
Hi Jojo, almost all employees under endevor can't log in on the system since yesterday, some were since last week. Attached is a screenshot on what appears on the screen.
![0-02-06-16d59e590a611e26d294d6b6b93d90af4a9fd37be26717d34c7142c75e32b281_ce1f0451](https://user-images.githubusercontent.com/69444972/91945847-a673aa80-ed31-11ea-91cb-8d6ca1714244.jpg)

**Comment by VCI-Jojo** [comment]
@emsarmiento I'll have this checked and resolved today, will keep you posted. Thank you.

**Comment by emsarmiento** [comment]
kindly also check - solar companies, they can't also log in. Thanks

**Comment by VCI-Jojo** [comment]
@emsarmiento As per our phone conversation earlier, we've applied fixes for the continuous loading screen, so kindly validate on your end if it is already working for Endevor and Solar Companies. Thank you.

**Comment by emsarmiento** [comment]
Hi Jojo, 

Just done checking if its working already, I had it also checked with the other employees as well. It's still the same
![0-02-06-40847a477ed1166dfde6bb589f933b6dad54b35a2739cee15134860fd708c392_ae529459](https://user-images.githubusercontent.com/69444972/92087439-0d5e9580-edfe-11ea-839c-d93620a7e785.jpg)
![0-02-06-4326845a731e79d2e987d5ac9b50c50ba447ade6ff4120cd53dc95dd5ff75807_a23dd19](https://user-images.githubusercontent.com/69444972/92087461-164f6700-edfe-11ea-9877-8c56fc1e96f0.jpg)

**Comment by VCI-Jojo** [comment]
@emsarmiento Please do Clear Cache on your browser by going to Settings and Clear Browsing Data (include cache) then open a new browser and check if it still loading on your end. It's already loading on my end. Thank you.

**Comment by emsarmiento** [comment]
Hi Jojo,

Copying in Armi who’s checking the status of tickets in Kodanda. Upon her checking, it is still the same.

Thanks.
