### ISSUE TITLE
Payroll Setting Customization Update needed (like Zen Hours)

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#240]
![image](https://user-images.githubusercontent.com/68258969/104892135-c805c380-59ac-11eb-8b59-bc7657a00ec2.png)

**Comment by VCI-Jojo** [comment]
@Annagwind payroll setting configuration can be seen on the payroll settings tab of the register, please see screenshots  below fore reference:

![rates config - payroll](https://user-images.githubusercontent.com/64577963/104898197-41ed7b00-59b4-11eb-967d-a33dc8c84c75.PNG)

![sss cutoff](https://user-images.githubusercontent.com/64577963/104898134-2f734180-59b4-11eb-83af-6646b4418b7d.PNG)
