### ISSUE TITLE
Limited Options for OT Claims

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#25]
Mr. Ferrer tried to apply for overtime since he rendered work duirng his rest day but it seems that his number of hours is limited.

The system should be able to provide more options since some employees may render work beyond the options provided in the system.

![OT ISSUE](https://user-images.githubusercontent.com/68258969/91979484-725fb000-ed58-11ea-9ea3-6fcd64e24e6b.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind May we get Mr. Ferrer's time in and out for the Rest Day? Thanks

**Comment by Annagwind** [comment]
August 30, 2020 8:AM-3PM . As per viber call there is no need to file for OT if the work rendered is not exceeding 8 hours.

**Comment by Annagwind** [comment]
Dear Sir Jojo,


Can you kindly change my roster to Admin on the employee setting ?

I was not able to apply for CTO availment and credit when I was an "Admin Tester" in the Roster so I changed it ManagerCTO to have CTO credit and availment but I now do not have Admin Access. Hence, I can't generate payroll register that I need to review by tomorrow for our report on Monday.

The system should also allow the site Admin to have CTO Manager functions since I am also eligible for CTO availment and credit.This is another issue that will be reported in the github.


Hoping you could assist for me retrieve my admin access while maintaining my manager cto functions as well by tomorrow morning.

Thanks .


Get Outlook for Android<https://aka.ms/ghei36>
