### ISSUE TITLE
Unable to Log In

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#26]
Employees of Guimaras Wind are unable to log in properly on time because the system keeps loading.

**Comment by VCI-Jojo** [comment]
@Annagwind Kindly advise if you are still experiencing the login concern today, as relayed to Abbie yesterday, there was a server issue with Google Cloud causing intermittent access, but it was resolved by them quickly so login should not be a problem already. Please advise. Thank you.

**Comment by Annagwind** [comment]
It still experienced by some employees from time to time. The quick punch of the kiosk most of the time keeps prompting "invalid" even if correct credetials is provided.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Annagwind** [comment]
Mr. Ferrer tried to log in this morning in the kiosk but is unable.

**Comment by VCI-Jojo** [comment]
@Annagwind Thank you for the additional information, team is investigating and we will provide feedback and/or resolution for the issue. I'll keep you posted.
