### ISSUE TITLE
Unable to view recent cut off

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#263]
![image](https://user-images.githubusercontent.com/68258969/105854623-13117d80-6022-11eb-8c1f-d833372ce986.png)

![image](https://user-images.githubusercontent.com/68258969/105854435-dba2d100-6021-11eb-9184-ad1a0db12863.png)

**Comment by VCI-Jojo** [comment]
@Annagwind Upon accessing the admin account, we can view the recent cutoffs. 

Please see screenshots for reference below for reference:

![GWPC - Sup](https://user-images.githubusercontent.com/64577963/105937085-d2e8e400-608f-11eb-9fd9-900ff337e5fa.jpg)

![GWPC Rank and File](https://user-images.githubusercontent.com/64577963/105937093-d5e3d480-608f-11eb-927b-b9b065413619.jpg)

Please do clear cache and check if the current cutoffs will be reflected. Thanks!

**Comment by VCI-Jojo** [comment]
@Annagwind Upon accessing the admin account, we can view the recent cutoffs. 

Please see screenshots for reference below for reference:

![GWPC - Sup](https://user-images.githubusercontent.com/64577963/105937085-d2e8e400-608f-11eb-9fd9-900ff337e5fa.jpg)

![GWPC Rank and File](https://user-images.githubusercontent.com/64577963/105937093-d5e3d480-608f-11eb-927b-b9b065413619.jpg)

Please do clear cache and check if the current cutoffs will be reflected. Thanks!

**Comment by Annagwind** [comment]
This is my current screen after clear cache.
[cid:image003.jpg@01D6F4AC.AD448730]


You may use my access to verify from your end.

Thanks
