### ISSUE TITLE
User Absent on Approved Leave

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#265]
User: Balatayo
![image](https://user-images.githubusercontent.com/68258969/106252774-94028c00-6251-11eb-8f05-7b323b2ae566.png)

**Comment by Annagwind** [comment]
user: ferrer

![image](https://user-images.githubusercontent.com/68258969/106268619-53613d80-6266-11eb-894a-d7263e9e0be2.png)

**Comment by Annagwind** [comment]
user: balatayo

![image](https://user-images.githubusercontent.com/68258969/107031920-eb72a000-67ed-11eb-8a2d-dd8e5666a9fd.png)

**Comment by Peterdelapena** [comment]
User: Ferrer
Period coverage: April 26, 2021 - May 10, 2021
Approved VL didn't reflect on DTR
![image](https://user-images.githubusercontent.com/84363701/121120447-21816880-c850-11eb-96a4-c178ef0b2000.png)
Supporting data on approved VL:
![image](https://user-images.githubusercontent.com/84363701/121120474-30681b00-c850-11eb-8c24-39a711c3b876.png)
![image](https://user-images.githubusercontent.com/84363701/121120507-44ac1800-c850-11eb-9599-3d1ca59fc644.png)

**Comment by AnyaCee** [comment]
issue closed
