### ISSUE TITLE
Quick Punch Issues

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#27]
The system prompts "invalid credentials" even though the correct credentials are given.

**Comment by VCI-Jojo** [comment]
Additional Info: As per our conversation, all users are experiencing the concern so they are currently using the web bundy feature of the Kiosk instead.

**Comment by Annagwind** [comment]
Kiosk keeps prompting invalid credentials. I used microsoft edge and google chrome browser.



![Quick Punch issue 2](https://user-images.githubusercontent.com/68258969/92720757-a873e400-f397-11ea-8557-34de404787a4.PNG)

**Comment by Annagwind** [comment]
The web bundy also prompted invalid credentials but was available again after a few hours.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by VCI-Jojo** [comment]
@Annagwind please observe if you will still encounter the issue upon time out later, thank you.
