### ISSUE TITLE
Previous Cut off cannot be accessed by User.

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#28]
Mr. Soque is trying to apply for punch alteration for the previous cut off but the system does not show any option for the cut offs. 

![DHS CUT OFF ISSUE](https://user-images.githubusercontent.com/68258969/92077665-75f24600-edef-11ea-9fb6-dc2d0941b737.PNG)

**Comment by Annagwind** [comment]
Mr. Templanza cannot also access the previous cut offs.

![KET](https://user-images.githubusercontent.com/68258969/92081182-47776980-edf5-11ea-9b65-53e0885d4086.jpg)

**Comment by VCI-Jojo** [comment]
@Annagwind I'll have this checked, linking it to ticket #18

**Comment by Annagwind** [comment]
Same issue with Mr. Coo.


![coo issue cut off](https://user-images.githubusercontent.com/68258969/92190683-59f4b000-ee94-11ea-8e2c-e64d15a12c69.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind Thank you for the additional information, team is investigating and we will provide feedback and/or resolution for the issue. I'll keep you posted.

**Comment by VCI-Jojo** [comment]
@Annagwind We've applied a patch for the previous cutoff, please validate on your end if it can be accessed already. Thank you.

**Comment by Annagwind** [comment]
Noted on this. The users can now access their previous cut off .

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by VCI-Jojo** [comment]
Thank you for the validation, will close this ticket.
