### ISSUE TITLE
Employee Register

### ISSUE THREAD

**Issue by emsarmiento** [vasavah/acenergykodanda#286]
kindly add employee registers for SACASOL
Plant Manager
Technical Engineer
HSSE Officer
Admin Specialist
Admin officer

kindly add employee registers for ISLASOL
Plant Manager
Technical Engineer
HSSE Officer
Admin Staff
Admin officer
3.kindly add employee registers MONTESOL
HSSE Officer
Admin Staff

kindly add employee registers SCCBWSI
Specialist, Proj. Implementation Engineer

**Comment by VCI-Jojo** [comment]
@emsarmiento clarification on this request, do they have different cutoff dates and payroll rules so that we create different registers for each position? Thank you.

**Comment by emsarmiento** [comment]
all have same cut off dates for solar and bw. But for payroll rules : SOLARS - all are monthly paid, for the BW's some are monthly paid, while others are daily paid
