### ISSUE TITLE
Upgrade of change of work schedule

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#29]
Upon conversation with our system operator, can we have the change of work schedule customize option to reflect 

1.They will have a drop down option which composes of the following:
1st Shift 6 am-2pm
2nd Shift 2 pm-10 pm
3rd Shift 10pm-6am
Staff Schedule 8am-5pm
Rest Day

This is to lessen the time to 

2. To 1 Month-1 Year set up/customization of the individual schedule.

![Work Around for Change of Work Schedule](https://user-images.githubusercontent.com/68258969/92208614-2464bc80-eebe-11ea-9efa-740c2dd07b92.PNG)

**Comment by Annagwind** [comment]
Upon conversation with our system operator, can we have the change of work schedule customize option to reflect

1.They will have a drop down option which composes of the following:
1st Shift 6 am-2pm
2nd Shift 2 pm-10 pm
3rd Shift 10pm-6am
Staff Schedule 8am-5pm
Rest Day

This is to lessen the time to customization of their schedule because their schedules  vary on the need of the operations. 

2.  1 Month-1 Year set up/customization of the individual schedule.
Can we have them the option to customize their schedule monthly or if possible yearly this is for them to have less applications of change of wrok schedule because the system gave them a Mon-Sat 8am to 5pm schedule which they need to update every 15 days.

**Comment by VCI-Jojo** [comment]
@Annagwind We will need to discuss this with Abbie as this will be an enhancement already, I'll coordinate an alignment meeting with her so we can discuss improvements. Thank you
