### ISSUE TITLE
ISSUE FOR FEB 16, 2021

### ISSUE THREAD

**Issue by emsarmiento** [vasavah/acenergykodanda#290]
Cannot log in on my credentials please see screenshot below:

![image](https://user-images.githubusercontent.com/69444972/108020862-414e1000-7058-11eb-81bb-6e2a77c5f409.png)

**Comment by VCI-Jojo** [comment]
@emsarmiento Kindly direct message me the credentials for the affected employee so we can investigate. Thank you.

**Comment by emsarmiento** [comment]
username: sarmiento.ev (this user cannot log in solar sites
