### ISSUE TITLE
Late but on time on record

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#292]
user:gallentes

![image](https://user-images.githubusercontent.com/68258969/108083994-aaf90900-70ae-11eb-9727-3943b70582d9.png)

**Comment by VCI-Jojo** [comment]
@Annagwind Schedule Shift In is 2:00 AM and Punch In is 1:48 PM so this will incur late, maybe the Shift In schedule is incorrect and should be 2:00 PM?
