### ISSUE TITLE
Option for Leave

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#3]
I tried to apply for different types of leave to test the system but I was only limited to apply for VACATION Leave.

1. I went to apply for leave application.
2. It only showed 1 option for leave application which is VACATION Leave.

The system should give provide the user the option to avail Vacation Leave (VL) , Sick Leave (SL) and Additional Day Off (ADO).

Device Details:
Laptop
Windows 7
Browser Google Chrome

**Comment by VCI-Jojo** [comment]
@Annagwind Upon checking the datasheets provided for the migration, only VL credits were supplied so this is the only leave that will be reflected on the accounts. You will need to add the leave type manually on the Leave Credits module moving forward. 

For reference: Page 30 on the Technical Manual.

**Comment by VCI-Jojo** [comment]
Closing this ticket.
