### ISSUE TITLE
CTO Application approved but reflects that it is rejected.

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#30]
Ms. Ganea tried to apply for CTO . The IS and HR approved her application for crediting but the system prompted that it is rejected. 

![GANEA CTO](https://user-images.githubusercontent.com/68258969/92293776-c0430680-ef58-11ea-93ed-68a6eea9b6c1.jpg)

**Comment by VCI-Jojo** [comment]
@Annagwind Please reference ticket #44 , you'll need to set ADO for CTO crediting. Thank you.
