### ISSUE TITLE
Payroll Configuration-Froze 

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#309]
User:ronzales

When clicking submit data cannot be processed as per Ms. Abbie

![viber_image_2021-03-01_14-23-58](https://user-images.githubusercontent.com/68258969/109460133-1a053300-7a9b-11eb-8c5a-f7f68f0ea27c.jpg)

**Comment by VCI-Jojo** [comment]
@Annagwind Upon checking using your account, can edit the values and save changes.
