### ISSUE TITLE
Invalid Pin even if credentials are correct

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#31]
The Quick Punch prompts Invalid Pin again even though credentials are correct.

![Invalid Pin9 5 2020](https://user-images.githubusercontent.com/68258969/92293888-760e5500-ef59-11ea-94fe-8ca440a2c351.PNG)

**Comment by Annagwind** [comment]
The Log In option also prompted the same even if the credentials are correct. This is the usual problem of the system from time to time. 

It functioned after a few hours.

**Comment by VCI-Jojo** [comment]
@Annagwind We've applied a patch for the Kiosk yesterday to prevent this, kindly validate if you can access already. Thank you.

**Comment by Annagwind** [comment]
The employees can no access the Kiosk. We’ll let you know if this issue arises again.

Thanks

**Comment by VCI-Jojo** [comment]
This is noted, will close the ticket. Thank you.
