### ISSUE TITLE
 Include application of updated schedule when applying for punch alteration

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#33]
Our operations department has very flexible schedule and changes instantaneously. The operators reconcile their records often times the following day and after every cut off through "Punch Alteration" .  Since the change of work schedule cannot be applied on the previous day (which will be subject to the approval of IS and HR) they just apply for punch alteration to input their records but they are out of schedule since they change in shift were instantaneous of were not changed on time.

When applying for punch alteration can we include that the final schedule will be applied along with the punch alteration?
Drop down down option to reflect the "SHIFT SCHEDULE":
1st Shift 6 am-2pm
2nd Shift 2 pm-10 pm
3rd Shift 10pm-6am
Staff Schedule 8am-5pm
Rest Day

Then after selecting their final schedule they will input their changes in the Time in and Time Out.This will be a more efficient way of reconciling the records whereas they will wait for the approval of the change of work schedule.

This is to avoid the entries to not be out of schedule because it might reflect to the record that a personnel is late / absent because the change of work schedule were not reconciled before the actual date.
![punch alteration to include updated schedule](https://user-images.githubusercontent.com/68258969/92316205-52174600-f023-11ea-9e2d-fb45f2d97c2e.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind For discussion with Abbie, for enhancement. Thanks
