### ISSUE TITLE
User customization of work schedule limited to the 15th day of the Month

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#34]
Upon checking the change of work schedule feature , Mr. Coo's account only allows him to change work schedule the following day until the 15th day while other users can customize it for a month.
Please see attached picture of screen shot of Mr. Coo's cutomization of work schedule option limited to the 15 day of the month.

![Changed of work schedule 15  days only](https://user-images.githubusercontent.com/68258969/92317235-34e97400-f031-11ea-8841-8ebf7465483d.PNG)

Please see attached picture of screen shot of Mr. Gallego's customization of work schedule not limited to the 15th day of the month.
![Changed of work sched whole month](https://user-images.githubusercontent.com/68258969/92317274-87c32b80-f031-11ea-8895-3e30f8073c29.PNG)

**Comment by Annagwind** [comment]
Mr. Ryan Tormis is also experiencing this issue . He cannot plot his schedule for the whole month.

**Comment by VCI-Jojo** [comment]
@Annagwind We've implemented a patch for this already, kindly validate on your end if resolved. Thank you.
