### ISSUE TITLE
Can apply change of work schedule with pending application to IS and HR

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#35]
Mr. Coo has a pending application application for his change of work schedule which was customized until the 15th day of the month. When I tried to access his account I've noticed that he can still submit application to customize his schedule. the system should prompt that he can no longer apply since he has a pending application.

If the changed of work schedule allows "Update of schedule" then prompts to the user that the previous application will automatically cancel then this wont be an issue. As long as the system can process that the previous application which may have been approved by the IS or HR that it will no longer be considered in the payroll register this upgrade will be helpful in the time keeping feature.

![can changed sched even if exiting application](https://user-images.githubusercontent.com/68258969/92317291-ae816200-f031-11ea-8e03-2d116f394df3.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind We've implemented a patch for this already, kindly validate on your end if resolved. Thank you.
