### ISSUE TITLE
Lost Admin Access of GW Admin due to changed in Roster as Manager CTO (to avail also CTO)

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#36]
I was not able to apply for CTO availment and credit when I was an "Admin Tester" in the Roster so I changed it ManagerCTO to have CTO credit and availment but I now do not have Admin Access. Hence, I can't generate payroll register.

The system should also allow the site Admin to have CTO Manager functions since I am also eligible for CTO availment and credit. ADMIN CTO should be an option to allow the admin to apply for CTO as well.

**Comment by VCI-Jojo** [comment]
@Annagwind We've added AdminCTO and I've changed your account to it, please validate if you have admin access and CTO already. Thank you.

**Comment by Annagwind** [comment]
Noted on this.Got my admin access back.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by VCI-Jojo** [comment]
Thank you for validating, will close this ticket.
