### ISSUE TITLE
Cannot Update work schedule on the previous day/cut off

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#37]
Some employees often time tend to reconcile their records the following day or the end of every cut off. Since they can only apply for "punch alteration" and not "Change of Work schedule" of the previous day/cut off . The register might result to late and absences in the records. 

The punch alteration features should also allow "Update in Schedule" so that the employee's records wont be out of schedule.
Example Situation:
Mr. Dave was not able to changed his work schedule due to plant emergency or slow internet to he opted to reconcile his records at the end of the cut off or the following day. He can no longer apply for Change of work Schedule since the system won't allow him to apply for the previous day or cut off. His schedule is still 8AM-5PM but his shift is 2pm-10pm when he applies to "Punch Alteration" and inputs 2pm-10 pm there will be late since he was not able to upadate his schedule.

If the punch alteration feature allows update in the schedule to also be filed it will be beneficial to the employees.

**Comment by VCI-Jojo** [comment]
@Annagwind Let's include this with the discussion with Abbie, since it is related to change work schedule.
