### ISSUE TITLE
Unable to access GWC kiosk

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#382]
We cleared cache . But the site cannot be accessed.

![image](https://user-images.githubusercontent.com/68258969/117812664-a9497680-b294-11eb-92c4-07b343a919a8.png)

**Comment by VCI-Jojo** [comment]
@Annagwind I was able to access the kiosk on my end. Thanks

![Kiosk - GWPC](https://user-images.githubusercontent.com/64577963/117813139-4c9a8b80-b295-11eb-87e8-e3abd6967bae.JPG)
