### ISSUE TITLE
Clarification on work rendered on a rest day in relation to CTO credit

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#39]
I would like to clarify if an employee (supervisor) reports for duty on a rest day or holiday can he/she apply for CTO credit ?ow will this automatically compute.

There should be an option for CTO crediting on a Rest day or Holiday for a supervisor.

![sunday](https://user-images.githubusercontent.com/68258969/92321820-acce9300-f05f-11ea-911f-78c6eec6fa96.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind We've implemented a patch for this already, kindly validate on your end if resolved. Thank you.
