### ISSUE TITLE
User was marked as late during OT during Special Holiday.

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#394]
User was marked as late during OT during Special Holiday.

He was called to report for work WTG Operation around 8:30am. Marked late by the system.
Since this is a holiday we are not necessarily required to report at 8:00am sharp.
user: quezon.rg

![image](https://user-images.githubusercontent.com/68258969/119280947-3f52a900-bc66-11eb-8ea0-14ac9e0616e5.png)

**Comment by Annagwind** [comment]
Generated Data

User is late based on consolidated data.


![image](https://user-images.githubusercontent.com/68258969/119463738-9e9edf00-bd74-11eb-8494-3511b4fe8a27.png)

**Comment by VCI-Jojo** [comment]
@Annagwind any adjustments for this one is on hold as per Charleen, pending rules on coming in for holidays based on schedule.
