### ISSUE TITLE
Basis of Data-9 Hours

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#396]
User: tormis.j
Cut off: May 11-25
Date for clarification May 16 -8 hrs NSD

![image](https://user-images.githubusercontent.com/68258969/119517253-0ae80580-bdaa-11eb-8d05-d969cbc26a8a.png)

Only 1 hr was applied but 9 hrs reflected

![image](https://user-images.githubusercontent.com/68258969/119517506-42ef4880-bdaa-11eb-877c-608cd4bd92c4.png)

**Comment by AnyaCee** [comment]
issue closed
