### ISSUE TITLE
Applied OT and total OT does not Match

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#397]
user: Tormis

![image](https://user-images.githubusercontent.com/68258969/119609402-1a0e9800-be2a-11eb-9bb2-c91285e61ded.png)

**Comment by Annagwind** [comment]
Applied OT
user: tormis

![image](https://user-images.githubusercontent.com/68258969/119610577-095f2180-be2c-11eb-81a6-d2a9d1fca982.png)


![image](https://user-images.githubusercontent.com/68258969/119610620-1aa82e00-be2c-11eb-9f10-e803d37bf19f.png)

**Comment by AnyaCee** [comment]
issue closed
