### ISSUE TITLE
Holiday Hours should not indicate NSD on Holiday

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#398]
When a user goes on duty for night shift on a holiday should the count be on the holiday with NSD not on Holiday Hours?

![image](https://user-images.githubusercontent.com/68258969/119609652-84bfd380-be2a-11eb-8559-2ef34289a0fd.png)

Ex. user: Tormis

![image](https://user-images.githubusercontent.com/68258969/119609830-cd778c80-be2a-11eb-9360-877b57f21ef5.png)

**Comment by Peterdelapena** [comment]
The same issue to another account but for a regular holiday on a night differential, shown below.
![image](https://user-images.githubusercontent.com/84363701/121119936-298cd880-c84f-11eb-94f9-e9b9e9b9a7fb.png)

**Comment by Peterdelapena** [comment]
Fixes validated
