### ISSUE TITLE
Unable to Access Account of Approver

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#4]
The account of Mr. Edwin Gallego cannot be accessed. 

1. I tried to log in to his account to check if the applications for approval went through.
2. I cannot access even though I have inputted correct credentials
User name : gallego.el and new password (I will send the new password via email if necessary)

The system should allow me access to his account since I have encoded correct credentials. 

Device Details:
Laptop
Windows 7
Browser Google Chrome

**Comment by VCI-Jojo** [comment]
@Annagwind Please send me the new password so I can check the account, just change it after the troubleshooting process. Thank you.

**Comment by VCI-Jojo** [comment]
Resolved as per Viber communication that all employees can access their accounts.
