### ISSUE TITLE
ManagerCTO user cannot apply for CTO

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#40]
Mr. Balatayo intends to apply for CTO but the system prompts that he should contact HR. 
Per verifying in the system he is a ManagerCTO so he should be able to apply for CTO Credit.

![JGB CTO ISSUE](https://user-images.githubusercontent.com/68258969/92340245-21e7aa00-f0ec-11ea-9b84-62021e31d321.PNG)

![JGB CTO Concern](https://user-images.githubusercontent.com/68258969/92340247-244a0400-f0ec-11ea-8c99-e24c84f207fd.png)

**Comment by VCI-Jojo** [comment]
@Annagwind Please reference ticket #44 , please set ADO for CTO Crediting. Thank you
