### ISSUE TITLE
Loan set via Deduction Feature did not reflect is payslip

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#403]
When the loan features had issues I set up a deduction of SSS Loan of Mr. Quezon via Earning/Deduction feature

![image](https://user-images.githubusercontent.com/68258969/120315811-5309a980-c30f-11eb-9dbf-04488f7b448b.png)

![image](https://user-images.githubusercontent.com/68258969/120315495-045c0f80-c30f-11eb-9dde-666fcf824387.png)

![image](https://user-images.githubusercontent.com/68258969/120315393-e5f61400-c30e-11eb-9948-c72bf776a6a4.png)

**Comment by AnyaCee** [comment]
issue closed
