### ISSUE TITLE
LWOP of User

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#404]
User forwarded a concern for his access which shows he is on LWOP and the number of Leave balance
User: galon.mf

![image](https://user-images.githubusercontent.com/68258969/120639116-985ee000-c4a3-11eb-971d-f9bc1920cfe1.png)

**Comment by VCI-Jojo** [comment]
@Annagwind was Galon late for the June 3 schedule? There's a rule for automatic LWOP for supervisors who are late for more than 2 hours from their shift. Kindly confirm. Thank you.

**Comment by Annagwind** [comment]
I believe he forgot t to time in/time out. Should Punch alteration option be open for him?

Anna Jeremae V. Ronzales | Administrative Officer
Guimaras Wind Corporation  | Brgy. Suclaran, San Lorenzo, Guimaras
Mobile: +63 917 818 7197 | Email: ***@***.******@***.***>



"Disclaimer:  This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email."

**Comment by Annagwind** [comment]
Additionally if the status is approved should there be an application for this ang not system generated?

***@***.***D75ADD.BED8F200]

Please clarify.

Thank

Anna Jeremae V. Ronzales | Administrative Officer
Guimaras Wind Corporation  | Brgy. Suclaran, San Lorenzo, Guimaras
Mobile: +63 917 818 7197 | Email: ***@***.******@***.***>



"Disclaimer:  This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email."

**Comment by VCI-Jojo** [comment]
@Annagwind as per Charleen's request, we've disable the LWOP rule for GWPC, please validate on your end. Thank you.
