### ISSUE TITLE
Unable to Approve OT

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#406]
I approved all OTs 
but everytime I log in again the approval keeps prompting as pending for approval

![image](https://user-images.githubusercontent.com/68258969/120946176-308fea00-c76e-11eb-9175-a58aea09dd0c.png)

after approval

![image](https://user-images.githubusercontent.com/68258969/120946209-4e5d4f00-c76e-11eb-944a-6e70ce804297.png)

**Comment by AnyaCee** [comment]
issue closed
