### ISSUE TITLE
Missing site information to a certain employee

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/acenergykodanda#407]
Empoyee# 30122 Site information doesn't appear on TAR.
![image](https://user-images.githubusercontent.com/84363701/121119349-07468b00-c84e-11eb-9a19-6c63d0882bf6.png)
TAR
![image](https://user-images.githubusercontent.com/84363701/121119476-470d7280-c84e-11eb-8ea7-c403c03bda90.png)
View Profile

**Comment by byron02** [comment]
![image](https://user-images.githubusercontent.com/51081259/121136675-7df08200-c868-11eb-91bd-67ae27f456a1.png)
Bug Type: Invalid

Org: GWPC

Cause of Bug: None

Approach: Need to regenerate from DTR if any update applied on the requirements of the DTR. (Example. Employee Information, Punch Records, etc)

Approached Applied: June 08, 2021

Pull Request: 

Branch:

**Comment by AnyaCee** [comment]
issue closed
