### ISSUE TITLE
CTO Credit to Operators on Day Shift

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#41]
Currently the rank and file operators who are reporting for duty on their day shift schedule files for advance OT as a work around since the day shift cannot be captured as overtime but the supervisory operators cannot file for CTO credit . Can the system allow for advance CTO credit option to the supervisory personnel?

**Comment by VCI-Jojo** [comment]
@Annagwind I'll discuss this with the team, will keep you posted. Thank you
