### ISSUE TITLE
Error in viewing previous cut off

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#410]
This is with admin access

EMployee : balatayo

![image](https://user-images.githubusercontent.com/68258969/121287821-e5fca200-c914-11eb-9b6c-c8a07eb57442.png)

**Comment by Annagwind** [comment]
user tried to view his previous cut off


User: balatayo
![image](https://user-images.githubusercontent.com/68258969/121288540-1f81dd00-c916-11eb-87e2-59ca36ad6892.png)

**Comment by AnyaCee** [comment]
issue has been resolved, marked as closed
