### ISSUE TITLE
Inconsistency of Cut off

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#411]
June 15 Payout =May 26-June 10 

Why is May 25 still included in the cut off?
Supervisor

![image](https://user-images.githubusercontent.com/68258969/121288225-98cd0000-c915-11eb-93af-38dc80ff5d3c.png)

user: balatayo
![image](https://user-images.githubusercontent.com/68258969/121288297-bd28dc80-c915-11eb-82f3-cacdb65f437d.png)

![image](https://user-images.githubusercontent.com/68258969/121288392-e0538c00-c915-11eb-978f-7b89d4c83e5d.png)

**Comment by AnyaCee** [comment]
issue has been resolved, marked as closed
