### ISSUE TITLE
Rest Day Should not be counted in Leave days

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#412]
user: gallentes

![image](https://user-images.githubusercontent.com/68258969/121354519-88427700-c961-11eb-9404-05e5d8e71b30.png)

![image](https://user-images.githubusercontent.com/68258969/121354668-aad49000-c961-11eb-8999-d97648baf77a.png)

**Comment by AnyaCee** [comment]
ISSUE HAS BEEN FIXED. MARKED AS CLOSED
