### ISSUE TITLE
Request for Customized cut off for Supervisors and Rank and File

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#413]
Cut off should be 
May 26-June 9= June 15th Payout

June 10-June25= June 30th Payout

Tried to do customization but system is unable to register
![image](https://user-images.githubusercontent.com/68258969/121513849-e59bfe00-ca1d-11eb-86a0-09e5af272a3a.png)

**Comment by Peterdelapena** [comment]
Fixes are done, the ticket will be marked as closed
![image](https://user-images.githubusercontent.com/84363701/122710155-4df6a500-d292-11eb-8f01-d8fa20fcac89.png)
