### ISSUE TITLE
Feature to edit time records using admin access to correct system errors are no longer available. Why?

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#419]
no edit functions anymore

![image](https://user-images.githubusercontent.com/68258969/123511443-fb632180-d6b3-11eb-80fd-77adf5a33bc2.png)

**Comment by Peterdelapena** [comment]
![image](https://user-images.githubusercontent.com/84363701/124114367-0dbbd180-da9f-11eb-89b0-a0627192466f.png)
Access to edit time records and Re-compute DTR is included, Ticket will be marked as closed
