### ISSUE TITLE
How to plot rest day on the change of work schedule feature

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#42]
Mr. Coo is currently plotting his schedule as an operator. He is suppose to have a rest day on September 14-15, 2020 (2 days) . He tried to remove all entries in the September 14-15 schedule thinking that once this is approved it would reflect that this is a rest day since no shift in and shift out schedule is plottes.

When his application is approved he noticed that September 14-15 , 2020 reflects that he has a 12am-12am schedule. does this already mean that this is a rest day ?

if not ,How can a personnel set his rest day on the schedule?

![BLC REST DAY ISSUE](https://user-images.githubusercontent.com/68258969/92383323-b2e87080-f140-11ea-8c7b-7b53fc00a49e.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind In this case, just remove the check mark for Sept 14-15 marking the dates as non working days.

**Comment by Annagwind** [comment]
Noted on this.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
