### ISSUE TITLE
Unable to Apply 30 Min Pre Shift OT

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#420]
user: ymalay

![image](https://user-images.githubusercontent.com/68258969/123512902-9eb83480-d6bc-11eb-94a5-dadf4673519e.png)

![image](https://user-images.githubusercontent.com/68258969/123512916-b099d780-d6bc-11eb-940d-b7f035b6d2a1.png)

**Comment by AnyaCee** [comment]
Validated as fixed, marked as closed
