### ISSUE TITLE
Data Basis 

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#425]
user: gallentes
cut off June 10-25 

![image](https://user-images.githubusercontent.com/68258969/123543888-4730cc00-d783-11eb-987c-50df07c01d4b.png)

**Comment by Annagwind** [comment]
same cut off as above

![image](https://user-images.githubusercontent.com/68258969/123544749-4a2dbb80-d787-11eb-849b-38b131c4c282.png)

**Comment by AnyaCee** [comment]
Validated as fixed, marked as closed
