### ISSUE TITLE
Quezon Time Entres for May 11-25 Cutoff

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/acenergykodanda#428]
Please check Randy Quezon for May 11-May 25 cutoff. Time entries is appearing as May 11 to May 31.

![image](https://user-images.githubusercontent.com/84363701/124408207-4e09a100-dd78-11eb-961c-2c29df793eb2.png)

**Comment by AnyaCee** [comment]
Ticket Marked as Closed
