### ISSUE TITLE
Customize leave credit

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#43]
Currently customizing the leave credit of the employee but I cant edit the used leave. 

I was suppose to encode the number of leaves for the entire year and the used leave portion to reflect the current number of leave but the used leave is uneditable.

![JGB LEAVE](https://user-images.githubusercontent.com/68258969/92385077-cb0dbf00-f143-11ea-8b37-b1ee131b9062.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind The used leaves is based on the actual leave applications done by the employee in the system so we can't make it editable. In this case, just encode the number of leaves left instead for the whole year.

**Comment by Annagwind** [comment]
Noted on this.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by VCI-Jojo** [comment]
Closing this ticket.
