### ISSUE TITLE
Correct Credentials Invalid

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#430]
This is to forward urgent concern.

GWC Users cannot access their account.
The systems prompt invalid even if correct credentials:

1. balatayo
2. ferrer
3. galon
4. quezon
5. cachuela

**Comment by Peterdelapena** [comment]
![image](https://user-images.githubusercontent.com/84363701/125013712-e49ed080-e09e-11eb-9a29-99f20977982f.png)

**Comment by AnyaCee** [comment]
Validated as fixed, marked as closed
