### ISSUE TITLE
ADO /CTO

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#44]
How can a personnel avail a CTO?
Can the CTO be a type of leave ? 

The CTO increases based on the approved CTO. Can the current number of days be reflected in the CTO crediting. This is to keep track of the number of CTO by the employee.

**Comment by VCI-Jojo** [comment]
@Annagwind As per our discussion yesterday, providing a guide on how to set CTO as a type of leave, in your case, you'll need to set the CTO for ADO.

You can do this by going to  HCM Settings > Click on the "Change CTO Crediting" > Select "ADO" from the dropdown menu > Save Changes

Change CTO Crediting Button

![Change CTO Crediting](https://user-images.githubusercontent.com/64577963/92428244-26ca5d80-f1c1-11ea-878b-aae98740a61d.png)

Select Leave for the CTO:

![Select Leave for CTO](https://user-images.githubusercontent.com/64577963/92428266-35187980-f1c1-11ea-902b-8241961ccd7d.png)

Let me know if you have any clarifications.

**Comment by Annagwind** [comment]
This was already customize as a type of leave but user Ms. Ganea still cannot apply for availment.

![cto  issue1](https://user-images.githubusercontent.com/68258969/92721430-aceccc80-f398-11ea-920b-fb2b5d59504a.jpg)

**Comment by VCI-Jojo** [comment]
@Annagwind Patch deployed, kindly validate if working already on your end. Thank you.

**Comment by Annagwind** [comment]
The CTO is credited to ADO.

Thanks
