### ISSUE TITLE
Correct credentials prompting error again

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#448]
User: ferrer.rf
password: Robertgwind1!

Correct credentials prompting error
![image](https://user-images.githubusercontent.com/68258969/130181830-704e9bce-cfb1-41f6-aae2-7e9cf5a67caa.png)

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,
Good day! This ticket is invalid, the user inputs the wrong credentials.

Here is the correct one:
User: ferrer.rf
password: RFFgwind1!

Kindly validate the credentials on your end. Thank you!

![image](https://user-images.githubusercontent.com/84363875/130187571-e9e47158-631d-4c43-9b12-fa85a61beeeb.png)
