### ISSUE TITLE
Leave Issue

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#45]
I am currently customizing the number of leave of an employee specifically Mr. Garganta . He has 11 VL left for 2020. When I try to customize this I entered 11 but when I saved it it reflected 48.

![AMG LEAVE](https://user-images.githubusercontent.com/68258969/92385935-63587380-f145-11ea-86b9-9263ec5d2d98.PNG)

**Comment by VCI-Jojo** [comment]
I've endorsed this to the support team for investigation. Thank you.

**Comment by VCI-Jojo** [comment]
@Annagwind We've applied a patch to correct this last night, please validate on your end. 

If the employee does not have any leave selection available, please check if the user has a  schedule assigned in the profile module. Thank you.

**Comment by Annagwind** [comment]
I was now able to customize this. thanks

**Comment by VCI-Jojo** [comment]
This is noted. Closing this ticket.
