### ISSUE TITLE
Leave Issue -Availment

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#46]
I customized the leave credit of Mr. Ymalay so he can avail SL and VL. 

but he has no options  when he applies for leave.

![dave leav 3](https://user-images.githubusercontent.com/68258969/92387540-4e311400-f148-11ea-9366-25a696504a2f.PNG)

**Comment by VCI-Jojo** [comment]
I've endorsed this to the support team for investigation. Thank you.

**Comment by VCI-Jojo** [comment]
@Annagwind We've applied a patch to correct this last night, please validate on your end.

**Comment by Annagwind** [comment]
He can now apply for leave. Thanks

**Comment by VCI-Jojo** [comment]
This is noted, will close this ticket. Thanks
