### ISSUE TITLE
Time Records to show the schedule also

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#47]
When viewing the time records it only shows the "rest days" and not the other current schedule.

Can the system show also the approved and current schedule of the employee in the Time Records area so that they would easily know their schedule and if they need to file for change of schedule immediately.

![BLC Time records to show current schedule](https://user-images.githubusercontent.com/68258969/92397111-c9022b00-f158-11ea-8090-6b7cea665deb.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind We've implemented a patch for this already, kindly validate on your end if resolved. Thank you.
