### ISSUE TITLE
Consolidated Time records

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#48]
When I tried to download the consolidated TAR for the supervisors I noticed the following:

1. Name of employee was left blank.
2. Some details of employee position jumped to other columns.
3. When employees are supervisor they should not be credited OT , holiday etc.

![Consolidated Payroll Register](https://user-images.githubusercontent.com/68258969/92397658-c6ec9c00-f159-11ea-831f-50c77f45a8bb.PNG)

**Comment by VCI-Jojo** [comment]
I've endorsed this to the support team for investigation. Thank you.

**Comment by VCI-Jojo** [comment]
@Annagwind We've implemented a patch for this already, kindly validate on your end if resolved. Thank you.
