### ISSUE TITLE
Holiday is NOT captured as  Pay Reg

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#49]
Holidays is not captured in the system. Ex. August 21, 2020 is a holiday which is set in the system but captured as under time. 

![PAY REG Holiday 2](https://user-images.githubusercontent.com/68258969/92600238-df85bf00-f2dd-11ea-899d-c33aeaed8550.PNG)
![PAY REG Holiday 3](https://user-images.githubusercontent.com/68258969/92600250-e280af80-f2dd-11ea-8525-8a8384c7f5aa.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind We've implemented a patch for this already, kindly validate on your end if resolved. Thank you.

**Comment by Annagwind** [comment]
Upon checking when i generate the individual TAR of Mr. Balatayo it still reflect as undertime.

![Individual TAR Holiday](https://user-images.githubusercontent.com/68258969/92871595-ac574300-f437-11ea-833b-12b6007e9a13.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind Kindly check if Undertime is still present. Thank you.

**Comment by Annagwind** [comment]
I just checked the individual TAR of Mr. Balatayo. No undertime anymore.

I’ll keep you posted if this happens again.

**Comment by VCI-Jojo** [comment]
This is noted. Closing this ticket.
