### ISSUE TITLE
Admin Edit not implemented

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#499]
![image](https://user-images.githubusercontent.com/68258969/141116067-674e7140-845f-4907-b7da-7cf912ebfb0e.png)
![image](https://user-images.githubusercontent.com/68258969/141116129-636b0321-b660-4f1f-be86-f23bec403fd2.png)

![image](https://user-images.githubusercontent.com/68258969/141116192-6aaef501-def9-4750-a833-d44de961f241.png)

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,

We are happy to inform you that this ticket has been pushed to production and are now considered resolved:

- Admin Edit not implemented

We encourage you to validate this on your end, so we can close the ticket for you. You may also contact us anytime if you have any other concerns or if you need any help with the system.
Thank you!
