### ISSUE TITLE
Unable to Punch In/Out of users with correct credentials

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#5]
The system will not allow the employees to Punch Out or Punch In using their username and pin even if the credentials are correct.

The following accounts with this issue are as follows
ronzales.ajv
templanza.kpe
overio.rm
soque.dh

The employees went to the link below for the pilot testing of the new system kiosk
https://kiosk.kodanda.cloud/#/login/gwpc

I cannot click submit button.
They system should allow the users to log in properly since they had correct credentials.

Device Details:
Laptop
Windows 10 Pro
Browser Google Chrome

The log in credentials of all users of GW Employees is already sent via email.

**Comment by VCI-Jojo** [comment]
Resolved as per Viber communication that all employees can access their accounts.
