### ISSUE TITLE
Individual Payroll Register

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#50]
Feedback for individual Pay Reg of Supervisors.

Even though the Holiday Management is set to be a holiday on August 21. There are still undertime in the results.
It does not reflect that a person is on travel or leave on a particular day when the individual register is downloaded.
OT hours, Holiday etc is credited.

![PAY REG Holiday 3](https://user-images.githubusercontent.com/68258969/92725877-5cc53880-f39f-11ea-857e-1c72df610a7a.PNG)

[SUPERVISOR PAY REG.xlsx](https://github.com/vasavah/acenergykodanda/files/5201351/SUPERVISOR.PAY.REG.xlsx)

**Comment by VCI-Jojo** [comment]
@Annagwind We've implemented a patch for this already, kindly validate on your end if resolved. Thank you.

**Comment by VCI-Jojo** [comment]
Closing this ticket re: Undertime
