### ISSUE TITLE
User cannot log in through Kiosk with correct credentials

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#500]
User cannot log in through Kiosk with correct credentials. He can only access his account via 2nd Link. Kiosk prompts his credential as invalid

![image](https://user-images.githubusercontent.com/68258969/141214151-d9936fd2-3c5a-4a7c-8f83-81edeede3b37.png)

**Comment by AnyaCee** [comment]
issue has been fixed, marked as closed.

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,
 
We are happy to inform you that this ticket has been pushed to production and are now considered resolved:

- User cannot log in through Kiosk with correct credentials 

We encourage you to validate this on your end, so we can close the ticket for you. You may also contact us anytime if you have any other concerns or if you need any help with the system.
Thank you!

**Comment by Annagwind** [comment]
Closing this ticket.
