### ISSUE TITLE
GWC Users Unable to Log In with Correct credentials

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#502]
user: Ymalay

![viber_image_2021-11-22_23-00-34-378](https://user-images.githubusercontent.com/68258969/142884450-b6c871f0-50d0-42cb-910f-7750eaeab597.jpg)

User: Magan

![viber_image_2021-11-22_23-01-18-627](https://user-images.githubusercontent.com/68258969/142884485-970194c7-622b-4256-b6d6-e026ba0f036f.jpg)

**Comment by AnyaCee** [comment]
Hi Ma'am anna,
Good morning. Upon Checking on our end, the issue is not occurring. Suggesting to clear cache.
Thank you.

The attached file is Mr. Ymalay's account.
![image](https://user-images.githubusercontent.com/84363875/142966129-c3059aab-fe99-40e7-a315-6faf97023f6e.png)

**Comment by Annagwind** [comment]
Clear Cache was done during the attempt to time in.
