### ISSUE TITLE
Continuous Loading 

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#505]
user: ferrer.rf

![image](https://user-images.githubusercontent.com/68258969/145910088-73045fd7-40a4-4473-a46b-632c35dc3646.png)

**Comment by AnyaCee** [comment]
Hi mam Anna,
 
Good day, we are happy to inform you that this support ticket has been pushed to production and is now considered resolved.
We encourage you to validate this on your end, so we can close the support ticket for you.

Proof of fixes:
![image](https://user-images.githubusercontent.com/84363875/146111783-f4ac86f5-9513-4f73-92c5-8b740c68bd8a.png)

**Comment by Annagwind** [comment]
This has been occurring more frequently now.
