### ISSUE TITLE
OT Approval does not go through

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#506]
![image](https://user-images.githubusercontent.com/68258969/146749945-59f8e286-4ced-450d-a18d-ea33fc48e164.png)

**Comment by AnyaCee** [comment]
Hi Ma'am anna, VCI QA's would like to request the credentials of the employee who experienced this issue. Thank you!

**Comment by Annagwind** [comment]
User: ronzales.ajv

The Admin of GWC Kodanda

Anna Jeremae V. Ronzales | Administrative Officer
Guimaras Wind Corporation  | Brgy. Suclaran, San Lorenzo, Guimaras
Mobile: +63 917 818 7197 | Email: ***@***.******@***.***>



"Disclaimer:  This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email."

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,

Good evening, We are happy to inform you that this ticket has been pushed to production and is now considered resolved.
We encourage you to validate this on your end. Thank you!

Proof of fixed:

![image](https://user-images.githubusercontent.com/84363875/146906507-6f022d70-c251-4af0-b759-3a72494e672c.png)
