### ISSUE TITLE
Continuous Loading in Kiosk for all employees when applying for alteration

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#509]
![image](https://user-images.githubusercontent.com/68258969/147015134-69fd1c81-ac7f-4016-90e0-88a0321dd6a5.png)

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,

Good morning, We are happy to inform you that this ticket has been pushed to production and is now considered resolved.
We encourage you to validate this on your end. Thank you!

Proof of fixed:
![image](https://user-images.githubusercontent.com/84363875/147028772-242c8e41-72e8-4095-8f4b-60c58e30593b.png)
