### ISSUE TITLE
Schedule of Mr. Gallego

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#51]
Mr. Gallego is set to be the same with other plant personnel . Monday to Saturday. Why is it that he has a Mon-Fri Schedule reflected to his time records?
![ELG SCHED](https://user-images.githubusercontent.com/68258969/92738184-5094a780-f3ae-11ea-9d22-6f32a718ac85.PNG)

![ELG SCHED 1](https://user-images.githubusercontent.com/68258969/92738464-88035400-f3ae-11ea-97bf-b8750056cbde.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind We've implemented a patch for this already, kindly validate on your end if resolved. Thank you.

**Comment by Annagwind** [comment]
Noted on this. He has now the same schedule as the other supervisors.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by VCI-Jojo** [comment]
This is noted. Closing this ticket.
