### ISSUE TITLE
HR Approval not going through

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#510]
user: ronzales
![image](https://user-images.githubusercontent.com/68258969/147029067-3cae8456-11b8-43c6-8680-0fb3ebe3bc39.png)

![image](https://user-images.githubusercontent.com/68258969/147029326-2572ffb1-ced7-4ab6-8fd1-0b733937fa02.png)

It takes multiple clicking for approval

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,

Good morning, this ticket has been already fixed yesterday.

Proof of fixed:
![image](https://user-images.githubusercontent.com/84363875/147032167-a8f95dbb-b307-41ba-8dfb-f38e7b6e8a6b.png)
Tested again today as of 11:37 A.M.
