### ISSUE TITLE
Inquiry on Pay Register

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#52]
I'll be exporting the results of the the payreg early to check the results. My question is if I lock this cut off for the checking and unlock it later will the applications after i unlock go through in this cut off?

![Pay Reg Question](https://user-images.githubusercontent.com/68258969/92919336-deca6580-f462-11ea-9648-10c9ba1cb1e2.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind Yes
