### ISSUE TITLE
Change Work Schedule 

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#53]
Can the customization of the change work schedule be set for the entire month and next 3 months (or 1 year if possible) ? This is to lessen the time for customization so that there will be minor applications for change of work schedule. 

![Schedule](https://user-images.githubusercontent.com/68258969/92935918-0843bb00-f47c-11ea-91c3-b3a2b3b39a62.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind I'm finalizing the Change Order with Abbie, will keep you posted regarding this. Thank you.
