### ISSUE TITLE
Kiosk Issue

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#54]
The quick punch and log in in the kiosk keeps prompting invalid pin even if correct credentials are given.

**Comment by VCI-Jojo** [comment]
@Annagwind We've deployed a patch for this, please validate on your end if it is already working. Thank you,

**Comment by Annagwind** [comment]
Employees experienced that they are unable to use the kiosk morning. Then the kiosk was available pass 8am so some employees were delayed in their entries.
