### ISSUE TITLE
Number of Hours inaccurate

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#547]
user:  ymalay.dj

![image](https://user-images.githubusercontent.com/68258969/167079366-a9f873fb-0159-44f2-967e-9f95a8a30227.png)

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,

Good day! 
I am happy to inform you that this ticket is already pushed to production and is considered resolved.
We encourage you to validate on your end and let us know if the issue still occurs. Thank you!

Kind regards,
Vasavah Support
