### ISSUE TITLE
WORK SCHEDULE AND TIME RECORDS

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#55]
Why is it that some employees can see their time records and schedule for an entire month in the time records option. And can also customize the schedule for an entire month. 

While other employees can only have access in the time records and change work schedule in the current cut off.

![SCHEDULE WHOLE MONTH](https://user-images.githubusercontent.com/68258969/93082803-23087080-f6c4-11ea-8f80-50db295064a7.PNG)
![SCHEDULE WHOLE MONTH 2](https://user-images.githubusercontent.com/68258969/93082794-200d8000-f6c4-11ea-9f62-696c12790401.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind This is currently based on their cutoffs so they'll have access to dates based on that.
