### ISSUE TITLE
Multiple Punch In/Out for one day is not allowed

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#56]
In the event the the first 8 hours of duty there is no time in and he incurs post shift OT.  Can he apply for post shift OT in the following days?

Ex.
Employee has an 8am-5pm schedule. He reports for work at 8am-5pm. There is no OT in his first entries, Then he will be requested to report for work at 7pm-9pm which is a post shift OT. 

The system does not allow multiple entries as observed by users, They cannot apply for the post shift duty the following day.

**Comment by VCI-Jojo** [comment]
@Annagwind Yes, this is the case with the system as it tags the new shift in and out for the next schedule already. In this case, employee needs to apply for Punch Alteration so new shift would be 8am to 9pm and then apply for post shift OT for 2 hours.

**Comment by Annagwind** [comment]
Noted. Will advise users.
