### ISSUE TITLE
Kiosk Issue-Ymalay

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#561]
![image](https://user-images.githubusercontent.com/68258969/170720117-a60c0e6e-d51e-48b9-8e6a-d96409895542.png)

Kindly check all accounts of GWC users.

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,

Good day! VCI would like to request further information regarding this issue.
The employee can't punch out? or just the display of may 27,2022?

Thank you!
Kind regards,
Vasavah Support

**Comment by Annagwind** [comment]
He punched in and out during that day.

But next day it is tagged as absent (I created a ticket for this.)

Thanks

Anna Jeremae V. Ronzales | HR & Administrative Officer
Guimaras Wind Corporation  | Brgy. Suclaran, San Lorenzo, Guimaras
Mobile: +63 917 818 7197 | Email: ***@***.******@***.***>



"Disclaimer:  This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email."

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,

Good day!
Upon checking the time records of sir Ymalay it has already have a punch alteration, thank you for the work around you've made. The issue regarding kiosk is already pushed to production and considered resolved.
We encourage you to validate on your end and let us know if the issue still occurs. Thank you!

Kind regards,
Vasavah Support
