### ISSUE TITLE
Absent even if Log in & Log out was facilitated - Ymalay

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#562]
user: ymalay

![image](https://user-images.githubusercontent.com/68258969/170816319-f082a1a2-b796-4414-834a-dda79b60f226.png)

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,

Good day! 
Upon checking the time records of sir Ymalay it has already have a punch alteration, thank you for the work around you've made. The issue regarding kiosk is already pushed to production and considered resolved.
We encourage you to validate on your end and let us know if the issue still occurs. Thank you!

Kind regards,
Vasavah Support
