### ISSUE TITLE
Cut off adjustment not implemented for June 15th Payout

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#563]
![image](https://user-images.githubusercontent.com/68258969/172071257-8638c495-16e1-4ed8-9b29-e618d7cd06c6.png)

Kindly check all GWC Users

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,

Good day! 
I am happy to inform you that this is already adjusted and is considered resolved.
We encourage you to validate on your end and let us know if the issue still occurs. Thank you!

Kind regards,
Vasavah Support
