### ISSUE TITLE
OB application of Derla Keeps returning for approval

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#564]
user: Derla

![image](https://user-images.githubusercontent.com/68258969/172177923-15e8d353-850f-444e-9c62-7247a095f333.png)

**Comment by AnyaCee** [comment]
Hi Ma'am Anna,

Good day! 
I am happy to inform you that this ticket is already pushed to production and is considered resolved.
We encourage you to validate on your end and let us know if the issue still occurs. Thank you!

Kind regards,
Vasavah Support
