### ISSUE TITLE
Unable to download individuat tar excel and pdf

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#57]
I am unable to download the tar records in excel and pdf.

![dl dtr](https://user-images.githubusercontent.com/68258969/93209823-3c2b2300-f791-11ea-888c-31230470fbec.PNG)

**Comment by Annagwind** [comment]
I also cannot download the consolidated report in this case.

**Comment by VCI-Jojo** [comment]
@Annagwind I've endorsed this to the development team. Thank you.

**Comment by Annagwind** [comment]
I can now download the files.

**Comment by VCI-Jojo** [comment]
This is noted. Closing this ticket.
