### ISSUE TITLE
Alteration Error noticed after approval

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#58]
There are instances that the user forgot to alter their time in and just altered their time out when the submitted the application and noticed only after approval. But since the application was approved by the IS and HR the employee can no longer retract the application. Can the system allow for alteration the 2nd time around?

**Comment by VCI-Jojo** [comment]
@Annagwind  IS or HR who approved can retract the approved alteration so employee can reapply. Please see screenshot for reference below. Thank you. 

![Retract Application](https://user-images.githubusercontent.com/64577963/93283235-b3e56600-f802-11ea-8ee1-24e78b51fe4b.PNG)

**Comment by Annagwind** [comment]
Unable to retract the alteration filed by Mr, Ferrer. His time in should have been 8:00 am not 8:25 am but he only fixed his time out.
He intends to fix the entries again the 2nd time around.

As traced by IS and HR  the retraction is no longer available to all previously approved applications.
![retract issue](https://user-images.githubusercontent.com/68258969/93287281-b00a1180-f80b-11ea-850a-8d2a29e33e56.PNG)


![retract issue 2](https://user-images.githubusercontent.com/68258969/93287294-b8624c80-f80b-11ea-8f67-b4624a965999.PNG)

![retract issue 3](https://user-images.githubusercontent.com/68258969/93287318-c7e19580-f80b-11ea-94c1-5517f7fdae39.PNG)
