### ISSUE TITLE
Unable to customize schedule of the 16th day

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#59]
Its the 16th day of the month but the operators still cannot customize their schedule. This will results to late and absences due to out of schedule time in/out in the next dtr results. 
![dtr issue](https://user-images.githubusercontent.com/68258969/93272525-43c9e680-f7e8-11ea-832f-389826726a18.PNG)

**Comment by Annagwind** [comment]
The 16-30 cut off is also unavailable in the time records section of the system. Hoping you've finalize the change of work schedule to accommodate 3 months or more in the customization.

**Comment by VCI-Jojo** [comment]
@Annagwind Yes, I'll be sending the Change Order document to Abbie within the day.

**Comment by Annagwind** [comment]
Employees are able to apply for change work schedule today. (For the current cut off only)

**Comment by Annagwind** [comment]
One of our operators is currently on day off. His schedule was not changed on time. It will reflect that he is absent in the next cut off.
