### ISSUE TITLE
How to cancel Leave Application if already approved

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#60]
I would to clarify if an employee files for leave the approved by IS and HR but due to plant emergency and personnal reasons how can the user cancel his/her leave? . The system should allow cancellation of approved leave.
![leave issue](https://user-images.githubusercontent.com/68258969/93278087-43d0e300-f7f6-11ea-8adc-fed980ebacc0.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind Approved leaves can only be retracted by the supervisor/manager who approved it, please reference ticket #58 for the retract application feature. Thank you.

**Comment by Annagwind** [comment]
Retraction of approved applications cannot be done by IS and HR as currently checked.
