### ISSUE TITLE
Icons not reflecting

### ISSUE THREAD

**Issue by BiancaDiesel** [vasavah/acenergykodanda#61]
Icons for punch in, punch out and the date today is not reflecting in the sytem. employees wasn't able to log-in

![16 September 2020](https://user-images.githubusercontent.com/68887837/93283283-cbbcea00-f802-11ea-84e6-160bb1fbf5ca.jpg)

**Comment by VCI-Jojo** [comment]
@BiancaDiesel I've endorsed this to the development team for checking, will keep you posted once resolved. Thank you.

**Comment by VCI-Jojo** [comment]
Upon initial investigation, we were able to see the Punch In and Out icons. In this case, please try to do clear cache on your browser and refresh and let us know if that resolves the concern. Thank you.

![CIPII](https://user-images.githubusercontent.com/64577963/93284121-8d282f00-f804-11ea-806b-03b1230ea9e6.jpg)

**Comment by BiancaDiesel** [comment]
Noted on this.

Thank you for your immediate response.
