### ISSUE TITLE
 Late in Records

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#64]
Upon checking the records, Mr. Galon's time in is 8:04 am but reflects as late in the records.

![late issue](https://user-images.githubusercontent.com/68258969/93293613-f1ee8400-f81a-11ea-8e35-f4b76ad0ab60.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind We've already applied a patch to address this, kindly validate on your end. Thank you.

**Comment by Annagwind** [comment]
There are still late records in the payroll register I generated.
