### ISSUE TITLE
Details of Consolidated report

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#65]
Details of some employees are not reflected on the pay register generated report.

![Consolidated Pag Reg Issue](https://user-images.githubusercontent.com/68258969/93329978-a0f98280-f850-11ea-9d27-cb858890b3be.PNG)

**Comment by Annagwind** [comment]
Same issue with Rank and File Consolidated Report

![Consolidated Pag Reg Issue 1](https://user-images.githubusercontent.com/68258969/93331719-53324980-f853-11ea-8f2d-c88e86c36cd1.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind We've already applied a patch to address this, kindly validate on your end. Thank you.

**Comment by Annagwind** [comment]
Details are now correct.
