### ISSUE TITLE
Leave Availed even though I did not use any leave during the Cut Off

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#66]
I was not able to avail any leave during this cut off but why is it that it reflects that I used 1.5 leave ?

![1 5 leave 2](https://user-images.githubusercontent.com/68258969/93330773-e4082580-f851-11ea-99ad-c9fb94dfa02f.PNG)
![1 5 leave](https://user-images.githubusercontent.com/68258969/93330788-eb2f3380-f851-11ea-9014-fe4c1ebe76eb.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind We've already applied a patch to address this, kindly validate on your end. Thank you.

**Comment by Annagwind** [comment]
The Leave which I did not applied for is still there when I generated the payroll register today.
