### ISSUE TITLE
Absent in Individual and Consolidated TAR even though Present in Records

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#67]
I was recorder as absent in the consolidated generated TAR even though I have records that I was present in my kodanda account.

![ABSENT ISSUE](https://user-images.githubusercontent.com/68258969/93331051-4b25da00-f852-11ea-9882-74f8e06300f5.PNG)

![ABSENT ISSUE 2](https://user-images.githubusercontent.com/68258969/93331043-495c1680-f852-11ea-93be-490127104e5c.PNG)

**Comment by Annagwind** [comment]
Same issue with the records of Ms. Ganea. Absent in Generated Report.


![CTG RECORDS 1](https://user-images.githubusercontent.com/68258969/93333431-e1a7ca80-f855-11ea-9a09-34f4b84f9b14.PNG)
![CTG RECORDS 2](https://user-images.githubusercontent.com/68258969/93333434-e2d8f780-f855-11ea-893b-7613dfb81038.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind We've already applied a patch to address this, kindly validate on your end. Thank you.

**Comment by Annagwind** [comment]
Noted . The absences are no longer reflected.

**Comment by Annagwind** [comment]
The absences on some personnel are due to change work schedule issues.
