### ISSUE TITLE
Result of Generated DTR from Kodanda and the data that should reflect on the register.

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#68]
Please see attached files for your reference. If you can also allot some time to discuss with me the coverage of each column I would to clarify some points.

[SEPT 1-15_20090115_GW_Payroll Instructions Reference.xlsx](https://github.com/vasavah/acenergykodanda/files/5236652/SEPT.1-15_20090115_GW_Payroll.Instructions.Reference.xlsx)
[SEPT 1-15_KODANDA.xlsx](https://github.com/vasavah/acenergykodanda/files/5236653/SEPT.1-15_KODANDA.xlsx)

**Comment by VCI-Jojo** [comment]
@Annagwind Let's set a meeting tomorrow to discuss, just let me know what time you'll be available. Thank you.

**Comment by Annagwind** [comment]
Hi Sir are you available for a quick call around 1pm ?

**Comment by VCI-Jojo** [comment]
@Annagwind Yes, let's discuss at 1PM. Thank you.

**Comment by Annagwind** [comment]
For your reference for our call.

**Comment by Annagwind** [comment]
[SEPT 1-15_20090115_GW_Payroll Instructions Reference  v2.xlsx](https://github.com/vasavah/acenergykodanda/files/5243507/SEPT.1-15_20090115_GW_Payroll.Instructions.Reference.v2.xlsx)
