### ISSUE TITLE
Leave Availed during cut off does not match in records

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#69]
Mr, Ymalay applied for leave total of 1.5 during Sept 1-15, cut off. But the register reflected that he has 1 leave availed during the cut off. 

![DJY 0 5 LEAVE](https://user-images.githubusercontent.com/68258969/93560422-bc7d9e00-f9b4-11ea-8ab2-f415a6eda806.PNG)
![DJY 1 LEAVE](https://user-images.githubusercontent.com/68258969/93560437-c3a4ac00-f9b4-11ea-9f6b-bff74e53643f.PNG)
![LEAVE](https://user-images.githubusercontent.com/68258969/93560460-cf906e00-f9b4-11ea-950a-98ac691cc786.PNG)
![leave 2](https://user-images.githubusercontent.com/68258969/93560798-855bbc80-f9b5-11ea-8cae-23c6939fd379.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind This has already been patched before, kindly validate on your end so we can close. Thank you.
