### ISSUE TITLE
Quick Punch Issue for all Users

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#7]
The system will not allow all Guimaras Wind Employees to use the Quick Punch function. 

Employees went to the below link to test the quick punch in /out.
https://kiosk.kodanda.cloud/#/login/gwpc
They used valid UseID  and PIN
It keeps appearing that the credentials are invalid.
They system should allow  to log in properly since we all had correct credentials.

Device Details:
Laptop
Windows 10
Browser Google Chrome

**Comment by VCI-Jojo** [comment]
Resolved as per Viber communication that all employees can access their accounts.
