### ISSUE TITLE
Log in and out not appearing on screen

### ISSUE THREAD

**Issue by emsarmiento** [vasavah/acenergykodanda#72]
Hi Jojo, 

We can't see any log in and out button on the screen today, please see screenshot, feedback button is no longer visible also
![image](https://user-images.githubusercontent.com/69444972/94323321-e42dc100-ffc7-11ea-85a4-231cb2964667.png)

**Comment by emsarmiento** [comment]
Hi!

in & out now visible except for the feedback button. Thanks

**Comment by VCI-Jojo** [comment]
@emsarmiento Noted regarding the In and Out, please check Feedback Button if visible already on your account. Thank you.

**Comment by VCI-Jojo** [comment]
@emsarmiento Anyone else you want to activate as testers? Please send names and companies for this. Thanks
