### ISSUE TITLE
Credential Access

### ISSUE THREAD

**Issue by Eviloria12** [vasavah/acenergykodanda#73]
Hi,

Requesting for your assistance regarding Nelly Bidey credentials. He can't log in to his credentials.

Here are the credentials we've received on your end. We would like to request the credential.

![image](https://user-images.githubusercontent.com/72014444/94533250-81f7e900-0271-11eb-87cf-a7791f1111b8.png)

Thank you.

**Comment by Eviloria12** [comment]
Here are the username and password we receive on your end.

Username: bidey.nv
Password: siHRqVmMrgtjWUtj

Thank you.

**Comment by VCI-Jojo** [comment]
@Eviloria12 We already sent a new password for Nelly Bidey last September 25, in any case, may I get your email address so I can send it to you directly. Thank you.

**Comment by Eviloria12** [comment]
Yes please.

It's viloria.ejv@acenergy.com.ph

Thank you.
________________________________
