### ISSUE TITLE
Shift Sched for SCC Bulk

### ISSUE THREAD

**Issue by emsarmiento** [vasavah/acenergykodanda#74]
Hi Jojo, 

Please see screenshot, work shifts seen are only Shift 1, Shift 1 and Shift 3 ( all bulk water companies have the same shift [image](https://user-images.githubusercontent.com/69444972/94658738-c947ad80-0335-11eb-83ba-6864735c4b0c.png)

**Comment by emsarmiento** [comment]
Also for the rejected leave application, EL, the number of leaves rejected was deducted on the leave balance, screenshot below:
![image](https://user-images.githubusercontent.com/69444972/94659144-6a366880-0336-11eb-97eb-5accdef48c10.png)
![image](https://user-images.githubusercontent.com/69444972/94659187-7c180b80-0336-11eb-95ab-2985b83b0a2b.png)

**Comment by VCI-Jojo** [comment]
@emsarmiento For all the Bulk Water companies, only 3 schedules were encoded on the migration data sheets, do you have additional schedule templates that needs to be there? Also I noticed that there are two Shift 1's, should we rename the second one to Shift 2? Reference again the data sheets, two shift 1's were encoded. Kindly advise. Thank you.

![LCC Schedules](https://user-images.githubusercontent.com/64577963/94879007-96b2c780-0491-11eb-8976-e477d9802dd9.PNG)

![HDP Schedules](https://user-images.githubusercontent.com/64577963/94879008-974b5e00-0491-11eb-96c7-cfca1f0a43d0.PNG)

![MCV Schedules](https://user-images.githubusercontent.com/64577963/94879000-94e90400-0491-11eb-8595-7ec9fb0bb4e6.PNG)

![SCC Schedules](https://user-images.githubusercontent.com/64577963/94879006-96b2c780-0491-11eb-9b32-eb0534a30b25.PNG)

**Comment by emsarmiento** [comment]
Yes please kindly rename the second shift to shift 2. Thanks

**Comment by VCI-Jojo** [comment]
Closing this ticket, Shift 1 to 3 appearing on all Bulk Water Instances.
