### ISSUE TITLE
IS or ADMIN/HR is unable to retract punch alterations

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#75]
When an employee makes an error when he/she applied for alteration and the application for alteration was already approved he/she cannot correct his/her entries which will result to absent or late.

IS or Admin/HR should be allowed to retract the approval.

![ALTERATION RETRACTION](https://user-images.githubusercontent.com/68258969/94662062-77555680-033a-11eb-9af5-12c66a10e698.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind the immediate supervisor who approved the application should be able to retract it, if you want IS or Admin/HR to be able to retract, they need to be secondary or alternative approver.

**Comment by Annagwind** [comment]
IS or Admin/HR are already set as approvers of the users.

**Comment by VCI-Jojo** [comment]
@Annagwind This has already been patched before, kindly validate on your end. Thank you.

**Comment by Annagwind** [comment]
Noted. This has been resolved

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
