### ISSUE TITLE
Customization of Change Work Schedule 

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#76]
It will be the 1st day of the next cut off tomorrow and users are unable to plot their schedule. This will impact the next cut off because it might reflect absent and late records since their schedule was not customized on time.

![Customization of Change Work Schedule](https://user-images.githubusercontent.com/68258969/94662987-b9cb6300-033b-11eb-8c13-e4b4ba15dbea.PNG)

**Comment by VCI-Jojo** [comment]
Linking this to ticket #78
