### ISSUE TITLE
GW Users cannot Log In to Kodanda

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#77]
Users are unable to log in to the kodanda system this morning.

**Comment by VCI-Jojo** [comment]
@Annagwind Are you still experiencing the concern? Please advise what time they were not able to login. Thanks

**Comment by Annagwind** [comment]
Unable to Log in at Kiosk Around 7:05 Log in (Web Bundy)  and Quick Punch

**Comment by VCI-Jojo** [comment]
This is noted, what time did the buttons return? Thank you.

**Comment by Annagwind** [comment]
Around 7:30 -8:00 am as per users.
