### ISSUE TITLE
Change of Work Schedule Issue

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#78]
User was trying to customize his schedule but the system prompted an error.

Hoping you could fix this today because he will report at 2pm and if this is not resolved it he will be out of schedule in the payroll register.

![BLC KODANDA](https://user-images.githubusercontent.com/68258969/94755943-bd58fb80-03c8-11eb-8ab4-df1d54ee00dc.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind do you have the feedback button present in your account? It would be best to use that so it will automatically send backend information to help our developers investigate and resolve. Also, what error message appeared?

**Comment by Annagwind** [comment]
Noted. I just used the feedback button a few minutes ago to report the issue.
