### ISSUE TITLE
Unable to Log In if Alteration is not approved

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#9]
The system will not allow all Guimaras Wind Employees to Log-In on the succeeding day if the alteration they filled on the previous day is not yet approved

Employees filed their alteration properly. If IS/HR are unable to approve the application before the next day they cannot log in/out. 

Device Details:
Laptop
Windows 10
Browser Google Chrome

**Comment by VCI-Jojo** [comment]
Additional Information: use case as per call is that employee was not able to punch out so applied for punch alteration but cannot punch in the next day's shift

**Comment by Annagwind** [comment]
templanza.kp
 
Previous day he forgot to log out.
Log out next day morning and filed alteration.

Cannot log in for the current day due to pending alteration.

Upon verification with the personnel he no longer experienced this.

**Comment by VCI-Jojo** [comment]
Thank you for the information, we have added validation for this that employees won't be able to apply for punch alteration if he/she has not logged out for the previous schedule. Closing this ticket as well.
