### ISSUE TITLE
Punch Alteration UnAvailable

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#94]
Mr. Overio , Mr. Galon and myself have punch alteration issues. 

![KODANDA RMO ALTERATION](https://user-images.githubusercontent.com/68258969/96812521-ccbee800-144e-11eb-840b-010a1f1c54b1.PNG)
![Punch Alteration](https://user-images.githubusercontent.com/68258969/96812533-cdf01500-144e-11eb-9412-06476b6d5ecf.PNG)
![AVR PUNCH ALTERATION](https://user-images.githubusercontent.com/68258969/96812818-e2341200-144e-11eb-8992-ea66133eada9.PNG)

**Comment by VCI-Jojo** [comment]
@Annagwind Upon checking the screenshots, there are no Punch Out's for the dates provided. Punch Alteration will only appear if we have both Punch In and Punch Out present. Thanks

**Comment by Annagwind** [comment]
Noted. How do we correct this . Because they were allowed to punch in and out the following day.

**Comment by VCI-Jojo** [comment]
@Annagwind I'll be sending the instructions later today on how to Edit Time Records from your end (Admin) so you can correct the punches. Thanks

**Comment by Annagwind** [comment]
Ok sir. Thanks . If this issue will be altered on my end, then I have an idea on to make the necessary correction, since  I was briefed by Ms. Abbie on this.
